---
title: "Exploratory H7_US_survey"
author: "CH"
date: "30/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(dplyr)
library(QuantPsyc) 
library(plm) # panel for regression
library(lmtest)
library(pglm) # panel logistic regression
library(pscl)
library(tidyr)
library(reshape2)
library(car)
library(MASS)
library(InformationValue) 
library(Epi)
library(ez)


data <- here::here("data/US_data.csv")
US_data <- readr::read_csv(data) %>%
  as.data.frame()

US_data <- US_data %>%
  mutate(vote = case_when(
  vote=='1' ~ 'Democrats',
  vote=='2' ~ 'Republicans',
  TRUE ~ 'Other'))

US_data <- US_data %>%
  mutate(unexp = case_when(
    unexp == "0" ~ "Expected",
    unexp == "1" ~ "Unexpected",
    unexp == "2" ~ "Neither expected nor unexpected"))

US_data <- US_data %>%
  mutate(gend = case_when(
    gend == "1" ~ "Female",
    gend == "2" ~ "Male",
    gend == "3" ~ "Non-binary"
  ))

US_data <- US_data %>%
  mutate(ethn = case_when(
    ethn == "1" ~ "Asian-American",
    ethn == "2" ~ "Black or African American",
    ethn == "3" ~ "Hispanic or Latino American",
    ethn == "4" ~ "Native American",
    ethn == "5" ~ "White or European American",
    ethn == "6" ~ "Other"
  ))

US_data <- US_data %>%
  mutate(degree =case_when(
    degree == "1" ~ "No degree",
    degree == "2" ~ "High School",
    degree == "3" ~ "Bachelor´s degree",
    degree == "4" ~ "Master´s degree",
    degree == "5" ~ "Doctoral degree",
    degree == "6" ~ "Professional degree",
    degree == "7" ~ "Other"
  ))

US_data <- US_data %>%
  mutate(employ = case_when(
    employ == "1" ~ "Working - paid employee",
    employ == "2" ~ "Working - self-employed",
    employ == "3" ~ "Not working - temporary layoff from a job",
    employ == "4" ~ "Not working - looking for a job",
    employ == "5" ~ "Not working - retired",
    employ == "6" ~ "Not working - disabled",
    employ == "7" ~ "Not working - student",
    employ == "8" ~ "Other"
  ))

US_data <- US_data %>%
  mutate(income = case_when(
    income == "1" ~ "$0 - $10,000",
    income == "2" ~ "$10,000 - $20,000",
    income == "3" ~ "$20,000 - $30,000",
    income == "4" ~ "$30,000 - $40,000",
    income == "5" ~ "$40,000 - $50,000",
    income == "6" ~ "over $50,000"
  ))

US <- US_data %>%
  mutate(cn = (cn_1 + cn_2 + cn_3 + cn_4 + cn_5)/5,
        secident = (secident_1 + secident_2 + secident_3 + secident_4 + secident_5 +
        secident_6 + secident_7 + secident_8 + secident_9 + secident_10)/10,
        ingroup_satis = (secident_4 + secident_5 + secident_6 + secident_7)/4,
        xeno = (xeno_1 + xeno_2 + xeno_3 + xeno_4)/4, 
        joy = (joy_1 + joy_2)/2,
        eff = (eff_1 + eff_2)/2) %>%
  mutate(z_cn = (cn - (mean(cn)/ sd(cn))),
         z_secident = (secident - (mean(secident)/ sd(secident))),
         z_fc_1_o_agr = (fc_1_o_agr - (mean(fc_1_o_agr) / sd(fc_1_o_agr))),
         z_fc_2_o_agr = (fc_2_o_agr -(mean (fc_2_o_agr)/ sd(fc_2_o_agr))),
         z_sd = (sd - (mean(sd)/ sd(sd))),
         z_cor_health = (cor_health - (mean(cor_health) / sd(cor_health))),
         z_cor_values = (cor_values - (mean(cor_values)/sd(cor_values))),
         z_joy = (joy - (mean(joy)/ sd(joy))),
         z_eff = (eff - (mean(eff) / sd(eff))),
         z_share = (share - (mean(share)/ sd(share))),
         z_donate = (donate - (mean(donate)/ sd(donate)))) %>%
  as.data.frame()
US

US$id <- as.factor(US$id)
US$time <- as.factor(US$time)

# subset data
US_t1_mod <- subset(US, time == "1" & vote == "Republicans" & unexp == "Unexpected")
US_t2_mod <- subset(US, time == "2" & vote == "Republicans" & unexp == "Unexpected")

US_t1_mod$id <- as.factor(US_t1_mod$id)
US_t1_mod$time <- as.factor(US_t1_mod$time)
US_t1_mod$vote <- as.factor(US_t1_mod$vote)

US_t2_mod$id <- as.factor(US_t2_mod$id)
US_t2_mod$time <- as.factor(US_t2_mod$time)
US_t2_mod$vote <- as.factor(US_t2_mod$vote)

# from long to wide dataset
US_wide <- reshape(US, direction = "wide", idvar = "id", timevar = "time")
US_wide_Rep <- subset(US_wide, vote.1 == "Republicans" & vote.2 == "Republicans")
US_wide_unexp_Rep <- subset(US_wide_Rep, unexp.1 == "Unexpected" & unexp.2 == "Unexpected")

# standardize variables which are on different scales (than 1 to 7)
US_wide$sd.2 = scale(US_wide$sd.2)
US_wide$fc_1_o_agr.1 = scale(US_wide$fc_1_o_agr.1)
US_wide$fc_1_o_agr.2 = scale(US_wide$fc_1_o_agr.2)
US_wide$fc_2_o_agr.1 = scale(US_wide$fc_2_o_agr.1)
US_wide$fc_2_o_agr.2 = scale(US_wide$fc_2_o_agr.2)
US_wide$cor_health.2 = scale(US_wide$cor_health.2)
US_wide$cor_values.2 = scale(US_wide$cor_values.2)
US_wide$donate.2 = scale(US_wide$donate.2)

# subset for rmANOVA
US_Rep <- subset(US, vote == "Republicans")

# standardize variables in dataset that use a different scale than 1 to 7

US_Rep$fc_1_o_agr = scale(US_Rep$fc_1_o_agr)
US_Rep$fc_2_o_agr = scale(US_Rep$fc_2_o_agr)
US_Rep$cor_health = scale(US_Rep$cor_health)
US_Rep$cor_values = scale(US_Rep$cor_values)

```

## Exploratory

# Collective narcissism  
```{r}
# descriptives by vote
descriptives3 <- US %>% 
  group_by(vote) %>%
  dplyr::select(., cn, secident, ingroup_satis, xeno, joy, eff, pi_1_own, pi_1_ave, pi_2_own, pi_2_ave, fc_1_s, fc_1_o_agr, fc_2_s, fc_2_o_agr) %>%
  summarise(., mean_cn = mean(cn), sd_cn = sd(cn), 
            mean_secident = mean(secident), sd_secident = sd(secident),
            mean_ingroup_satis = mean(ingroup_satis), sd_ingroup_satis = sd(ingroup_satis), 
            mean_xeno = mean(xeno), sd_xeno = sd(xeno),
            mean_joy = mean(joy), sd_joy = sd(joy),
            mean_eff = mean(eff), sd_eff = sd(eff),
            mean_pi_1_own = mean(pi_1_own), sd_pi_1_own = sd(pi_1_own),
            mean_pi_1_ave = mean(pi_1_ave), sd_pi_1_ave = sd(pi_1_ave),
            mean_pi_2_own = mean(pi_2_own), sd_pi_2_own = sd(pi_2_own),
            mean_pi_2_ave = mean(pi_2_ave), sd_pi_2_ave = sd(pi_2_ave),
            mean_fc_1_s = mean(fc_1_s), sd_fc_1_s = sd(fc_1_s),
            mean_fc_1_o_agr = mean(fc_1_o_agr), sd_fc_1_o_agr = sd(fc_1_o_agr),
            mean_fc_2_s = mean(fc_2_s), sd_fc_2_s = sd(fc_2_s),
            mean_fc_2_o_agr = mean(fc_2_o_agr), sd_fc_2_o_agr = sd(fc_2_o_agr))
descriptives3

# descriptives by vote and time
descriptives4 <- US %>% 
  group_by(vote, time) %>%
  summarise(., mean_cn = mean(cn), sd_cn = sd(cn), 
            mean_secident = mean(secident), sd_secident = sd(secident), 
            mean_xeno = mean(xeno), sd_xeno = sd(xeno),
            mean_joy = mean(joy), sd_joy = sd(joy),
            mean_eff = mean(eff), sd_eff = sd(eff),
            mean_pi_1_own = mean(pi_1_own), sd_pi_1_own = sd(pi_1_own),
            mean_pi_1_ave = mean(pi_1_ave), sd_pi_1_ave = sd(pi_1_ave),
            mean_pi_2_own = mean(pi_2_own), sd_pi_2_own = sd(pi_2_own),
            mean_pi_2_ave = mean(pi_2_ave), sd_pi_2_ave = sd(pi_2_ave),
            mean_fc_1_s = mean(fc_1_s), sd_fc_1_s = sd(fc_1_s),
            mean_fc_1_o_agr = mean(fc_1_o_agr), sd_fc_1_o_agr = sd(fc_1_o_agr),
            mean_fc_2_s = mean(fc_2_s), sd_fc_2_s = sd(fc_2_s),
            mean_fc_2_o_agr = mean(fc_2_o_agr), sd_fc_2_o_agr = sd(fc_2_o_agr))
descriptives4

# two-way anova: vote and unexp on cn

anova_cn <- aov(cn ~ time + vote + unexp + Error(id/time), data = US)
summary(anova_cn)

# t-test cn by vote
cn.t.test <- t.test(cn ~ vote, data = US_t2)
cn.t.test

# effect size

t<-cn.t.test$statistic[[1]]
df<-cn.t.test$parameter[[1]]
r <- sqrt(t^2/(t^2+df))
round(r, 3)

# without outliers fc_1_s 
descriptives5 <- US_t1_clean %>% 
  group_by(vote, time) %>%
  summarise(., mean_fc_1_s = mean(fc_1_s), sd_fc_1_s = sd(fc_1_s))
descriptives5

# without outliers fc_1_o_agr
descriptives6 <- US_t1_clean2 %>% 
  group_by(vote, time) %>%
  summarise(., mean_fc_1_o_agr = mean(fc_1_o_agr), sd_fc_1_o_agr = sd(fc_1_o_agr))
descriptives6

# plot
ggplot(US_t2, aes(x=cn, fill=vote))+
  geom_histogram(aes(y=..density..),binwidth=1, alpha=.5, position="identity") +
  labs(x= "Collective narcissism", y= "Frequency") +
  scale_fill_manual(name = "Vote", 
      labels = c("Democratic Party", "Republican Party", NA), 
      values = c("#58a6a6", "#efa355", NA)) +
  theme_light()
```

# Collective narcissism on FC and behavioural intention
```{r}
# fc_1_o_agr & fc_2_o_agr

# rmANOVA
fc_1.rm <- aov(fc_1_o_agr ~ time + cn + secident + Error(id/time), data = US_Rep)
summary(fc_1.rm)

fc_2.rm <- aov(fc_2_o_agr ~ time + cn + secident + cor_health + Error(id/time), data = US_Rep)
summary(fc_2.rm)

# --> see script "MLM_US_survey.Rmd" for alternative approach using MLM




# multiple regression

# fc_1_o_agr
fc_1_cn.mod <- lm(fc_1_o_agr.2 ~ cn.2, data = US_wide_Rep) # N = 52
summary(fc_1_cn.mod)
plot(fc_1_cn.mod)
ncvTest(fc_1_cn.mod)# homoscedasticity assumption not violated

# without outliers
US_wide_Rep_clean1 <- US_wide_Rep %>%
  filter(., id!= "p180" & id!= "p122" & id!= "p148")

fc_1_cn.mod_clean <- lm(fc_1_o_agr.2 ~ cn.2, data = US_wide_Rep_clean1) # N = 49
summary(fc_1_cn.mod_clean)
plot(fc_1_cn.mod_clean)

# adding secident and fc_1_o_agr.1 (with outliers removed)
fc_1_cn.mod2 <- lm(fc_1_o_agr.2 ~ cn.2 + secident.2 + fc_1_o_agr.1, data = US_wide_Rep)
summary(fc_1_cn.mod2)
plot(fc_1_cn.mod2)
confint(fc_1_cn.mod2)
ncvTest(fc_1_cn.mod2) # homoscedasticity assumption not violated
vif(fc_1_cn.mod2)

# without outlier removal
fc_1_cn.mod2a <- lm(fc_1_o_agr.2 ~ cn.2 + secident.2 + fc_1_o_agr.1, data = US_wide_Rep)
summary(fc_1_cn.mod2a)
confint(fc_1_cn.mod2a)

bootResults0 <- Boot(fc_1_cn.mod2, R = 10000)
summary(bootResults0)
boot.ci(bootResults0, type = "bca", index = 2)
boot.ci(bootResults0, type = "bca", index = 3)
boot.ci(bootResults0, type = "bca", index = 4)

# fc_2_o_agr
fc_2_cn.mod <- lm(fc_2_o_agr.2 ~ cn.2, data = US_wide_Rep) # N = 52
summary(fc_2_cn.mod)
plot(fc_2_cn.mod)

# without outlier
US_wide_Rep_clean2 <- US_wide_Rep %>%
  filter(., id != "p122")

fc_2_cn.mod_clean <- lm(fc_2_o_agr.2 ~ cn.2, data = US_wide_Rep_clean2) # N = 51
summary(fc_2_cn.mod_clean)

# adding secident, fc_2_o_agr t1 and cor_health
fc_2_cn.mod2 <- lm(fc_2_o_agr.2 ~ cn.2 + secident.2 + fc_2_o_agr.1 + cor_health.2, data = US_wide_Rep) # N = 51
summary(fc_2_cn.mod2)
confint(fc_2_cn.mod2)
plot(fc_2_cn.mod2) # issues with linearity 

# --> bootstrap 
bootReg <- function(formula, data, indices)
  {
    d <- data [i,]
    fit <- lm(formula, data = d)
    return(coef(fit))
  }

bootResults <- Boot(fc_2_cn.mod2, R = 10000)
summary(bootResults)
boot.ci(bootResults, type = "bca", index = 2)
boot.ci(bootResults, type = "bca", index = 3)
boot.ci(bootResults, type = "bca", index = 4)
boot.ci(bootResults, type = "bca", index = 5)

# If more than one predictor: boot.ci(bootResults, type = "bca", index = 1) intercept; 
# boot.ci(bootResults, type "bca", index = 2) first predictor; boot.ci(bootResults, 
# type = "bca", index = 3) second predictor etc

# Note that the confidence interval isn’t symmetrical because our data isn’t 
# perfectly normal. Thus, when you report them make sure to note that they are 
# 95% bootstrap bca confidence intervals. Also note that the quantiles reported 
# in the output are linear quantiles

# https://ademos.people.uic.edu/Chapter12.html#5_what_can_we_do_to_remedy_this



# behavioural intention

# repeated measures ANOVA
sign.rm <- aov(sign ~ time + cn + secident + Error(id/time), data = US_Rep)
summary(sign.rm)

# --> see script "MLM_US_survey.Rmd" for alternative approach using MLM



# Multiple regression


sign_cn.mod <- glm(sign.2 ~ cn.2, data = US_wide_Rep, family = "binomial")
summary(sign_cn.mod)
exp(coef(sign_cn.mod))
exp(confint(sign_cn.mod))
pscl::pR2(sign_cn.mod) ["McFadden"]

# adding secident and sign.1 
sign_cn.mod2 <- glm(sign.2 ~ cn.2 + secident.2 + sign.1, data = US_wide_Rep, family = "binomial")
summary(sign_cn.mod2)
exp(coef(sign_cn.mod2))
exp(confint(sign_cn.mod2))
pscl::pR2(sign_cn.mod2) ["McFadden"] # values > .40 mean that the model fits the data very well)
car::vif(sign_cn.mod2) 

bootResults <- Boot(sign_cn.mod2, R = 10000)
summary(bootResults)
boot.ci(bootResults, type = "bca", index = 2)
boot.ci(bootResults, type = "bca", index = 3)
boot.ci(bootResults, type = "bca", index = 4)


# predictions based on cn-values
sign_cn_pred <- data.frame(cn.2 = 4, secident.2 = 6, sign.1 = 0)
predict(sign_cn.mod2, sign_cn_pred, type = "response")

# predictions for each individual in dataset

predicted <- predict(sign_cn.mod2, US_wide_Rep, type = "response")
predicted

# model diagnostics
optimal <- optimalCutoff(US_wide_Rep$sign.2, predicted) [1] 
optimal 

# sensitivity and specificity
sensitivity(US_wide_Rep$sign.2, predicted)
specificity(US_wide_Rep$sign.2, predicted)

# total miscalculation error rate
misClassError(US_wide_Rep$sign.2, predicted, threshold = optimal) 

# ROC curve
plotROC(US_wide_Rep$sign.2, predicted) 
```











# ### FURTHER AND OLD CALCULATIONS



# False consensus on empowerment and behavioural intention
```{r}
# joy
joy_fc_1.mod <- lm(joy.2 ~ fc_1_o_agr.2, data = US_wide_Rep)
summary(joy_fc_1.mod)
plot(joy_fc_1.mod)
ncvTest(joy_fc_1.mod) # homoscedasticity assumption not violated
confint(joy_fc_1.mod)

joy_fc_1.mod2 <- lm(joy.2 ~ fc_1_o_agr.2 + cor_values.2, data = US_wide_Rep)
summary(joy_fc_1.mod2)
plot(joy_fc_1.mod2)
confint(joy_fc_1.mod2)

# without outlier
US_wide_Rep_clean3 <- US_wide_Rep %>%
  filter(., id!= "p022" & id!= "p159" & id!= "p192")

joy_fc_1.mod_clean <- lm(joy.2 ~ fc_1_o_agr.2, data = US_wide_Rep_clean3)
summary(joy_fc_1.mod_clean)
plot(fc_1_cn.mod_clean)
ncvTest(joy_fc_1.mod_clean) # homoscedasticity assumption not violated
confint(joy_fc_1.mod_clean)

joy_fc_1.mod2_clean <- lm(joy.2 ~ fc_1_o_agr.2 + cor_values.2, data = US_wide_Rep_clean3)
summary(joy_fc_1.mod2_clean)
plot(fc_1_cn.mod_clean)
confint(joy_fc_1.mod2_clean)


joy_fc_2.mod <- lm(joy.2 ~ fc_2_o_agr.2, data = US_wide_Rep)
summary(joy_fc_2.mod)
ncvTest(joy_fc_1.mod) # homoscedasticity assumption not violated
confint(joy_fc_2.mod)
plot(joy_fc_2.mod)

joy_fc_2.mod2 <- lm(joy.2 ~ fc_2_o_agr.2 + cor_values.2, data = US_wide_Rep)
summary(joy_fc_2.mod2)
confint(joy_fc_2.mod2)
plot(joy_fc_2.mod2)

# without outlier
US_wide_Rep_clean4 <- US_wide_Rep %>%
  filter(., id!= "p192" & id!= "p159" & id!= "p171")

joy_fc_2.mod_clean <- lm(joy.2 ~ fc_2_o_agr.2, data = US_wide_Rep_clean4)
summary(joy_fc_2.mod_clean)

joy_fc_2.mod2_clean <- lm(joy.2 ~ fc_2_o_agr.2 + cor_values.2, data = US_wide_Rep_clean4)
summary(joy_fc_2.mod2_clean)


# eff

eff_fc_1.mod <- lm(eff.2 ~ fc_1_o_agr.2, data = US_wide_Rep)
summary(eff_fc_1.mod)
plot(eff_fc_1.mod)
ncvTest(eff_fc_1.mod) # homoscedasticity assumption not violated
confint(eff_fc_1.mod)

eff_fc_1.mod2 <- lm(eff.2 ~ fc_1_o_agr.2 + cor_health.2, data = US_wide_Rep)
summary(eff_fc_1.mod2)
plot(eff_fc_1.mod2)
confint(eff_fc_1.mod2)

# without outlier
US_wide_Rep_clean5 <- US_wide_Rep %>%
  filter(., id!= "p154" & id!= "p073" & id!= "p049")

eff_fc_1.mod_clean <- lm(eff.2 ~ fc_1_o_agr.2, data = US_wide_Rep_clean5)
summary(eff_fc_1.mod_clean)
plot(eff_fc_1.mod_clean)
confint(eff_fc_1.mod_clean)

eff_fc_1.mod2_clean <- lm(eff.2 ~ fc_1_o_agr.2 + cor_health.2, data = US_wide_Rep_clean5)
summary(eff_fc_1.mod2_clean)
plot(eff_fc_1.mod2_clean)
confint(eff_fc_1.mod2_clean)

bootResults2 <- Boot(eff_fc_1.mod2, R = 10000)
summary(bootResults2)
boot.ci(bootResults2, type = "bca", index = 2)
boot.ci(bootResults2, type = "bca", index = 3)



eff_fc_2.mod <- lm(eff.2 ~ fc_2_o_agr.2, data = US_wide_Rep)
summary(eff_fc_2.mod)
plot(eff_fc_2.mod)
confint(eff_fc_2.mod)

eff_fc_2.mod2 <- lm(eff.2 ~ fc_2_o_agr.2 + cor_health.2, data = US_wide_Rep)
summary(eff_fc_2.mod2)
plot(eff_fc_2.mod2)
confint(eff_fc_2.mod2)

bootResults3 <- Boot(eff_fc_2.mod2, R = 10000)
summary(bootResults3)
boot.ci(bootResults3, type = "bca", index = 2)
boot.ci(bootResults3, type = "bca", index = 3)


# behavioural intention (fc_1_o_agr)
sign_fc_1.mod <- glm(sign.2 ~ fc_1_o_agr.2, data = US_wide_Rep, family = "binomial")
summary(sign_fc_1.mod)
exp(coef(sign_fc_1.mod))
exp(confint(sign_fc_1.mod))
pscl::pR2(sign_fc_1.mod) ["McFadden"]

# adding sign.1 
sign_fc_1.mod2 <- glm(sign.2 ~ fc_1_o_agr.2 + sign.1, data = US_wide_Rep, family = "binomial")
summary(sign_fc_1.mod2)
exp(coef(sign_fc_1.mod2))
exp(confint(sign_fc_1.mod2))
pscl::pR2(sign_fc_1.mod2) ["McFadden"] # values > .40 mean that the model fits the data very well)
car::vif(sign_fc_1.mod2) 

bootResults4 <- Boot(sign_fc_1.mod2, R = 10000)
summary(bootResults4)
boot.ci(bootResults4, type = "bca", index = 2)
boot.ci(bootResults4, type = "bca", index = 3)

# predictions based on cn-values
sign_fc_1_pred <- data.frame(fc_1_o_agr.2 = 7, sign.1 = 0)
predict(sign_fc_1.mod2, sign_fc_1_pred, type = "response")

# predictions for each individual in dataset

predicted <- predict(sign_fc_1.mod2, US_wide_Rep, type = "response")
predicted

# model diagnostics
optimal <- optimalCutoff(US_wide_Rep$sign.2, predicted) [1] 
optimal 

# sensitivity and specificity
sensitivity(US_wide_Rep$sign.2, predicted)
specificity(US_wide_Rep$sign.2, predicted)

# total miscalculation error rate
misClassError(US_wide_Rep$sign.2, predicted, threshold = optimal) 

# ROC curve
plotROC(US_wide_Rep$sign.2, predicted)


# behavioural intention (fc_2_o_agr)
sign_fc_2.mod <- glm(sign.2 ~ fc_2_o_agr.2, data = US_wide_Rep, family = "binomial")
summary(sign_fc_2.mod)
exp(coef(sign_fc_2.mod))
exp(confint(sign_fc_2.mod))
pscl::pR2(sign_fc_2.mod) ["McFadden"]

# adding sign.1 
sign_fc_2.mod2 <- glm(sign.2 ~ fc_2_o_agr.2 + sign.1, data = US_wide_Rep, family = "binomial")
summary(sign_fc_2.mod2)
exp(coef(sign_fc_2.mod2))
exp(confint(sign_fc_2.mod2))
pscl::pR2(sign_fc_2.mod2) ["McFadden"] # values > .40 mean that the model fits the data very well)
car::vif(sign_fc_2.mod2) 

bootResults5 <- Boot(sign_fc_2.mod2, R = 10000)
summary(bootResults5)
boot.ci(bootResults5, type = "bca", index = 2)
boot.ci(bootResults5, type = "bca", index = 3)


# predictions based on cn-values
sign_fc_2_pred <- data.frame(fc_2_o_agr.2 = 4, sign.1 = 1)
predict(sign_fc_2.mod2, sign_fc_2_pred, type = "response")

# predictions for each individual in dataset

predicted <- predict(sign_fc_2.mod2, US_wide_Rep, type = "response")
predicted

# model diagnostics
optimal <- optimalCutoff(US_wide_Rep$sign.2, predicted) [1] 
optimal 

# sensitivity and specificity
sensitivity(US_wide_Rep$sign.2, predicted)
specificity(US_wide_Rep$sign.2, predicted)

# total miscalculation error rate
misClassError(US_wide_Rep$sign.2, predicted, threshold = optimal) 

# ROC curve
plotROC(US_wide_Rep$sign.2, predicted) 
```

# Empowerment and behavioural intention
```{r}
# behavioural intention (joy)
sign_joy.mod <- glm(sign.2 ~ joy.2, data = US_wide_Rep, family = "binomial")
summary(sign_joy.mod)
exp(coef(sign_joy.modd))
exp(confint(sign_joy.mod))
pscl::pR2(sign_joy.mod) ["McFadden"]

# adding sign.1 
sign_joy.mod2 <- glm(sign.2 ~ joy.2 + sign.1, data = US_wide_Rep, family = "binomial")
summary(sign_joy.mod2)
exp(coef(sign_joy.mod2))
exp(confint(sign_joy.mod2))
pscl::pR2(sign_joy.mod2) ["McFadden"] # values > .40 mean that the model fits the data very well)
car::vif(sign_joy.mod2) 

bootResults6 <- Boot(sign_joy.mod2, R = 10000)
summary(bootResults6)
boot.ci(bootResults6, type = "bca", index = 2)
boot.ci(bootResults6, type = "bca", index = 3)

# predictions based on cn-values
sign_joy_pred <- data.frame(joy.2 = 1, sign.1 = 0)
predict(sign_joy.mod2, sign_joy_pred, type = "response")

# predictions for each individual in dataset

predicted <- predict(sign_joy.mod2, US_wide_Rep, type = "response")
predicted

# model diagnostics
optimal <- optimalCutoff(US_wide_Rep$sign.2, predicted) [1] 
optimal 

# sensitivity and specificity
sensitivity(US_wide_Rep$sign.2, predicted)
specificity(US_wide_Rep$sign.2, predicted)

# total miscalculation error rate
misClassError(US_wide_Rep$sign.2, predicted, threshold = optimal) 

# ROC curve
plotROC(US_wide_Rep$sign.2, predicted) 


# behavioural intention (eff)
sign_eff.mod <- glm(sign.2 ~ eff.2, data = US_wide_Rep, family = "binomial")
summary(sign_eff.mod)
exp(coef(sign_eff.mod))
exp(confint(sign_eff.mod))
pscl::pR2(sign_eff.mod) ["McFadden"]

# adding sign.1 
sign_eff.mod2 <- glm(sign.2 ~ eff.2 + sign.1, data = US_wide_Rep, family = "binomial")
summary(sign_eff.mod2)
exp(coef(sign_eff.mod2))
exp(confint(sign_eff.mod2))
pscl::pR2(sign_eff.mod2) ["McFadden"] # values > .40 mean that the model fits the data very well)
car::vif(sign_eff.mod2) 

bootResults7 <- Boot(sign_eff.mod2, R = 10000)
summary(bootResults7)
boot.ci(bootResults7, type = "bca", index = 2)
boot.ci(bootResults7, type = "bca", index = 3)

# predictions based on cn-values
sign_eff_pred <- data.frame(eff = 4, sign.1 = 1)
predict(sign_eff.mod2, sign_eff_pred, type = "response")

# predictions for each individual in dataset

predicted <- predict(sign_eff.mod2, US_wide_Rep, type = "response")
predicted

# model diagnostics
optimal <- optimalCutoff(US_wide_Rep$sign.2, predicted) [1] 
optimal 

# sensitivity and specificity
sensitivity(US_wide_Rep$sign.2, predicted)
specificity(US_wide_Rep$sign.2, predicted)

# total miscalculation error rate
misClassError(US_wide_Rep$sign.2, predicted, threshold = optimal) 

# ROC curve
plotROC(US_wide_Rep$sign.2, predicted) 
```

# Explorative
```{r}
# explorative: cn on signing 
sign_joint.mod1 <- glm(sign.2 ~ cn.2 + joy.2, data = US_wide_Rep, family = "binomial")
summary(sign_joint.mod1)
exp(coef(sign_joint.mod1))
exp(confint(sign_joint.mod1))
pscl::pR2(sign_joint.mod1) ["McFadden"]

# explorative: removing joy, adding secident
sign_joint.mod2 <- glm(sign.2 ~ cn.2 + secident.2, data = US_wide_Rep, family = "binomial")
summary(sign_joint.mod2)
exp(coef(sign_joint.mod2))
exp(confint(sign_joint.mod2))
pscl::pR2(sign_joint.mod2) ["McFadden"]
car::vif(sign_joint.mod2) 

# explorative: adding joy
sign_joint.mod3 <- glm(sign.2 ~ cn.2 + secident.2 + joy.2, data = US_wide_Rep, family = "binomial")
summary(sign_joint.mod3)
exp(coef(sign_joint.mod3))
exp(confint(sign_joint.mod3))
pscl::pR2(sign_joint.mod3) ["McFadden"]
car::vif(sign_joint.mod3) 

bootResults8 <- Boot(sign_joint.mod3, R = 10000)
summary(bootResults8)
boot.ci(bootResults8, type = "bca", index = 2)
boot.ci(bootResults8, type = "bca", index = 3)
boot.ci(bootResults8, type = "bca", index = 4)

# explorative: removing joy, adding sign.1
sign_joint.mod4 <- glm(sign.2 ~ cn.2 + secident.2 + sign.1, data = US_wide_Rep, family = "binomial")
summary(sign_joint.mod4)
exp(coef(sign_joint.mod4))
exp(confint(sign_joint.mod4))
pscl::pR2(sign_joint.mod4) ["McFadden"]
car::vif(sign_joint.mod4) 

# explorative: predicting sign.1
sign_joint.mod5a <- glm(sign.1 ~ joy.1, data = US_wide_Rep, family = "binomial")
summary(sign_joint.mod5a)
exp(coef(sign_joint.mod5a))
exp(confint(sign_joint.mod5a))
pscl::pR2(sign_joint.mod5a) ["McFadden"]
car::vif(sign_joint.mod5a)

bootResults9 <- Boot(sign_joint.mod5a, R = 10000)
summary(bootResults9)
boot.ci(bootResults9, type = "bca", index = 2)


sign_joint.mod5 <- glm(sign.1 ~ cn.1, data = US_wide_Rep, family = "binomial")
summary(sign_joint.mod5)
exp(coef(sign_joint.mod5))
exp(confint(sign_joint.mod5))
pscl::pR2(sign_joint.mod5) ["McFadden"]
car::vif(sign_joint.mod5) 

# explorative: adding joy.1
sign_joint.mod6 <- glm(sign.1 ~ cn.1 + joy.1, data = US_wide_Rep, family = "binomial")
summary(sign_joint.mod6)
exp(coef(sign_joint.mod6))
exp(confint(sign_joint.mod6))
pscl::pR2(sign_joint.mod6) ["McFadden"]
car::vif(sign_joint.mod6) 

# explorative: removing joy.1, adding secident.1
sign_joint.mod7 <- glm(sign.1 ~ cn.1 + secident.1, data = US_wide_Rep, family = "binomial")
summary(sign_joint.mod7)
exp(coef(sign_joint.mod7))
exp(confint(sign_joint.mod7))
pscl::pR2(sign_joint.mod7) ["McFadden"]
car::vif(sign_joint.mod7) 

bootResults10 <- Boot(sign_joint.mod7, R = 10000)
summary(bootResults10)
boot.ci(bootResults10, type = "bca", index = 2)


# predictions based on cn-values
sign_joint_pred <- data.frame(fc_2_o_agr.2 = 1, cn.2 = 7, joy.2 = 7, sign.1 = 1)
predict(sign_joint.mod2, sign_joint_pred, type = "response")

# predictions for each individual in dataset

predicted <- predict(sign_joint.mod2, US_wide_Rep, type = "response")
predicted

# model diagnostics
optimal <- optimalCutoff(US_wide_Rep$sign.2, predicted) [1] 
optimal 

# sensitivity and specificity
sensitivity(US_wide_Rep$sign.2, predicted)
specificity(US_wide_Rep$sign.2, predicted)

# total miscalculation error rate
misClassError(US_wide_Rep$sign.2, predicted, threshold = optimal) 

# ROC curve
plotROC(US_wide_Rep$sign.2, predicted) 
```

# Further anaylsis: CN on joy & eff
```{r}
joy_cn.mod <- lm(joy.2 ~ cn.2, data = US_wide_Rep)
summary(joy_cn.mod)
confint(joy_cn.mod)
plot(joy_cn.mod)
ncvTest(joy_cn.mod)# homoscedasticity assumption not violated

joy_cn.mod2 <- lm(joy.2 ~ cn.2 + secident.2, data = US_wide_Rep)
summary(joy_cn.mod2)
confint(joy_cn.mod2)
plot(joy_cn.mod2)
ncvTest(joy_cn.mod2) # homoscedasticity assumption not violated

joy_cn.mod3 <- lm(joy.2 ~ cn.2 + secident.2 + cor_values.2, data = US_wide_Rep)
summary(joy_cn.mod3)
confint(joy_cn.mod3)
plot(joy_cn.mod3)
ncvTest(joy_cn.mod3) # homoscedasticity assumption not violated

bootResults11 <- Boot(joy_cn.mod3, R = 10000)
summary(bootResults11)
boot.ci(bootResults11, type = "bca", index = 2)
boot.ci(bootResults11, type = "bca", index = 3)
boot.ci(bootResults11, type = "bca", index = 4)

eff_cn.mod <- lm(eff.2 ~ cn.2, data = US_wide_Rep)
summary(eff_cn.mod)
plot(eff_cn.mod)
     
bootReg <- function(formula, data, indices)
  {
    d <- data [i,]
    fit <- lm(formula, data = d)
    return(coef(fit))
  }

bootResults <- Boot(eff_cn.mod, R = 10000)
summary(bootResults)
boot.ci(bootResults, type = "bca", index = 2)

eff_cn.mod2 <- lm(eff.2 ~ cn.2 + secident.2, data = US_wide_Rep)
summary(eff_cn.mod2)
plot(eff_cn.mod2)

eff_cn.mod3 <- lm(eff.2 ~ cn.2 + secident.2 + cor_health.2, data = US_wide_Rep)
summary(eff_cn.mod3)
confint(eff_cn.mod3)
plot(eff_cn.mod3)

bootResults <- Boot(eff_cn.mod3, R = 10000)
summary(bootResults)
boot.ci(bootResults, type = "bca", index = 2)
boot.ci(bootResults, type = "bca", index = 3)
```














# OLD

# panel design regression
```{r}
is.data.frame(US)
dim(US)
str(US)
summary(US)

# computing differences in fc_1_o_agr and cn
diff_fc_1_o_agr <- US_t2_mod$fc_1_o_agr - US_t1_mod$fc_1_o_agr
diff_fc_2_o_agr <- US_t2_mod$fc_2_o_agr - US_t1_mod$fc_2_o_agr
diff_secident <- US_t2_mod$secident - US_t1_mod$secident
diff_cn <- US_t2_mod$cn - US_t1_mod$cn
diff_sd <- US_t2_mod$sd - US_t1_mod$sd
diff_cor_values <- US_t2_mod$cor_values - US_t1_mod$cor_values
diff_cor_health <- US_t2_mod$cor_health - US_t1_mod$cor_health
diff_joy <- US_t2_mod$joy - US_t1_mod$joy
diff_eff <- US_t2_mod$eff - US_t1_mod$eff
diff_sign <- US_t2_mod$sign - US_t1_mod$sign
diff_share <- US_t2_mod$share - US_t1_mod$share
diff_donate <- US_t2_mod$donate - US_t1_mod$donate

# regression fc_1_o_agr (step 1)
diff_fc_1 <- lm(diff_fc_1_o_agr ~ diff_cn)
coeftest(diff_fc_1, vcov = vcovHC, type = "HC1")
summary(diff_fc_1)


diff_fc_1alt <- lm(diff_fc_1_o_agr ~  diff_cn + diff_secident + diff_sd + diff_cor_values + diff_cor_health)
coeftest(diff_fc_1alt, vcov = vcovHC, type = "HC1")
coef_lmbeta <- lm.beta(diff_fc_1alt)
coef_lmbeta
confint(diff_fc_1alt)
summary(diff_fc_1alt)
plot(diff_fc_1alt)

# fixed effect regression fc_1_o_agr, keeping effects across entities constant (step 2)
diff_fc_12 <- plm(fc_1_o_agr ~ cn + id, 
                   data = US,
                   index = c("id", "time"),
                   model = "within")
coeftest(diff_fc_12, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_12)

# time fixed effect regression fc_1_o_agr, keeping effects across entities and time constant (step 3)
diff_fc_13 <- plm(fc_1_o_agr ~ sd + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_13, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_13)

# adding control variables

diff_fc_14 <- plm(fc_1_o_agr ~ sd + cor_values + cor_health + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_14, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_14)

diff_fc_15 <- plm(fc_1_o_agr ~ sd + cor_values + cor_health + secident + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_15, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_15)

diff_fc_16 <- plm(fc_1_o_agr ~ sd + cor_values + cor_health + secident + cn + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_16, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_16)

diff_fc_17 <- plm(fc_1_o_agr ~ secident + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_17, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_17)

diff_fc_18 <- plm(fc_1_o_agr ~ secident + cn + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_18, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_18)



# regression fc_2_o_agr (step 1)
diff_fc_2 <- lm(diff_fc_2_o_agr ~ diff_cn)
coeftest(diff_fc_2, vcov = vcovHC, type = "HC1")
summary(diff_fc_2)

diff_fc_2alt <- lm(diff_fc_2_o_agr ~  diff_cn + diff_secident + diff_sd + diff_cor_values + diff_cor_health)
coeftest(diff_fc_2alt, vcov = vcovHC, type = "HC1")
coef_lmbeta2 <- lm.beta(diff_fc_2alt)
coef_lmbeta2
confint(diff_fc_2alt)
summary(diff_fc_2alt)

# fixed effect regression fc_2_o_agr, keeping effects across entities constant (step 2)
diff_fc_22<- plm(fc_2_o_agr ~ cn + id, 
                   data = US,
                   index = c("id", "time"),
                   model = "within")
coeftest(diff_fc_22, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_22)

# time fixed effect regression fc_2_o_agr, keeping effects across entities and time constant (step 3)
diff_fc_23 <- plm(fc_2_o_agr ~ sd + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_23, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_23)

# adding control variables

diff_fc_24 <- plm(fc_2_o_agr ~ sd + cor_values + cor_health + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_24, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_24)

diff_fc_25 <- plm(fc_2_o_agr ~ sd + cor_values + cor_health + secident + sd + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_25, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_25)

diff_fc_26 <- plm(fc_2_o_agr ~ sd + cor_values + cor_health + secident + cn + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_26, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_26)

diff_fc_27 <- plm(fc_2_o_agr ~ secident + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_27, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_27)

diff_fc_28 <- plm(fc_2_o_agr ~ secident + cn + id + time,
                    data = US, 
                    index = c("id", "time"),
                    model = "within",
                    effect = "twoways")
coeftest(diff_fc_28, vcov = vcovHC, type = "HC1")
r.squared(diff_fc_28)


# logistic regression
US_panel <- pdata.frame(US, index = c("id", "time"))
sign.mod <- pglm(sign ~ sd, 
             data = US_panel,
             family = "binomial")
summary(sign.mod)

sign.mod2 <- pglm(sign ~ sd + cor_values + cor_health, 
             data = US_panel,
             family = "binomial")
summary(sign.mod2)

sign.mod3 <- pglm(sign ~ sd + cor_values + cor_health + secident, 
             data = US_panel,
             family = "binomial")
summary(sign.mod3)

sign.mod4 <- pglm(sign ~ sd + cor_values + cor_health + secident + cn, 
             data = US_panel,
             family = "binomial")
summary(sign.mod4)
exp(coef(sign.mod4))
exp(confint(sign.mod4))
```



```{r}
# fc_1_o_agr
fc_1_cn.mod <- lm(scale(fc_1_o_agr.2) ~ scale(cn.2), data = US_wide_unexp_Rep) # N = 44
summary(fc_1_cn.mod)
plot(fc_1_cn.mod)

# without outliers
US_wide_unexp_Rep_clean1 <- US_wide_unexp_Rep %>%
  filter(., id!= "p122" & id!= "p156" & id!= "p180")

fc_1_cn.mod_clean <- lm(scale(fc_1_o_agr.2) ~ scale(cn.2), data = US_wide_unexp_Rep_clean1) # N = 41
summary(fc_1_cn.mod_clean)

# adding secident and fc_1_o_agr t1
fc_1_cn.mod2 <- lm(scale(fc_1_o_agr.2) ~ scale(cn.2) + scale(secident.2) + scale(fc_1_o_agr.1), data = US_wide_unexp_Rep_clean1)
summary(fc_1_cn.mod2)
plot(fc_1_cn.mod2)

# adding further covariates
fc_1_cn.mod3 <- lm(scale(fc_1_o_agr.2) ~ scale(cn.2) + scale(secident.2) + scale(fc_1_o_agr.1) + scale(sd.2) + scale(cor_values.2) + scale(cor_health.2), data = US_wide_unexp_Rep_clean1)
summary(fc_1_cn.mod3)


# fc_2_o_agr
fc_2_cn.mod <- lm(scale(fc_2_o_agr.2) ~ scale(cn.2), data = US_wide_unexp_Rep) # N = 44
summary(fc_2_cn.mod)
plot(fc_2_cn.mod)

# without outliers
US_wide_unexp_Rep_clean2 <- US_wide_unexp_Rep %>%
  filter(., id!= "p151" & id!= "p153" & id!= "p186")

fc_2_cn.mod_clean <- lm(scale(fc_2_o_agr.2) ~ scale(cn.2), data = US_wide_unexp_Rep_clean2) # N = 41
summary(fc_2_cn.mod_clean)

# adding secident and fc_2_o_agr.1
fc_2_cn.mod2 <- lm(scale(fc_2_o_agr.2) ~ scale(cn.2) + scale(secident.2) + scale(fc_2_o_agr.1), data = US_wide_unexp_Rep_clean2)
summary(fc_2_cn.mod2)
plot(fc_2_cn.mod2)

# without outliers
US_wide_unexp_Rep_clean3 <- US_wide_unexp_Rep_clean2 %>%
  filter(., id!= "p024" & id!= "p035" & id!= "p173")

fc_2_cn.mod2_clean <- lm(scale(fc_2_o_agr.2) ~ scale(cn.2) + scale(secident.2) + scale(fc_2_o_agr.1), data = US_wide_unexp_Rep_clean3) # N = 38
summary(fc_2_cn.mod2_clean)  

# adding further covariates
fc_2_cn.mod3 <- lm(scale(fc_2_o_agr.2) ~ scale(cn.2) + scale(secident.2) + scale(fc_2_o_agr.1) + scale(sd.2) + scale(cor_values.2) + scale(cor_health.2), data = US_wide_unexp_Rep_clean2)
summary(fc_2_cn.mod3)
```

